VXPATTERN = r'https?://(?:www\.)?(?:twitter\.com|x\.com)/([^/]+)/status/(\d+)(?:/photo/\d)?'
VXREPLACEMENT = r'https://vxtwitter.com/\1/status/\2'
DDREELPATTERN = r'https?://(?:www\.)?instagram\.com\/reel\/([a-zA-Z0-9_-]+)(\/\?igshid=[a-zA-Z0-9_-]+)?'
DDREELREPLACEMENT = r'https://ddinstagram.com/reel/\1\2'
DDPOSTPATTERN= r'https://(?:www\.)?instagram\.com/p/([a-zA-Z0-9_-]+)(/\?utm_source=ig_web_copy_link)?'
DDPOSTREPLACEMENT = r'https://ddinstagram.com/p/\1'
TTPATTERN = r'https:\/\/(?:www\.|vm\.)?tiktok\.com\/@([^\/]+)\/video\/(\d+)'
TTREPLACEMENT = r'https://vxtiktok.com/@\1/video/\2'
VMPATTERN = r'https:\/\/vm\.tiktok\.com\/([\[A-Za-z0-9]+)'
VMREPLACEMENT = r'https://vm.vxtiktok.com/\1'
PXPATTERN = r'https:\/\/(?:www\.)?pixiv\.net\/(?:en\/)?(?:artworks|member_illust)\/(\d+)'
PXREPLACEMENT = r'https://phixiv.net/artworks/\1'
RXPATTERN = r'https?:\/\/(?:www\.)?(reddit\.com)\/(.*)'
RXREPLACEMENT = r'https://rxddit.com/\2'