version: '1'
services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - TOKEN=
      - OSUSECRET=
      - CLIENTID=
      - ADMIN=
      - QUOTECHANNELID=
      - MODCHANNEL=
      - OSUCHANNEL=
      - CATAPIKEY=
    env_file:
      - .env
    volumes:
      - persistent:/bot/persistent

volumes:
  persistent:
