version: '1'
services:
  embed-fixer:
    build: .
    restart: unless-stopped
    environment:
      # Don't use quotation marks
      - TOKEN=your bot token here
      - ADMIN=your discord userid here
    env_file:
      - .env
